---
- hosts: win
  vars:
    username: myusername
  tasks:
    - name: "Add the my user"
      win_user:
       name: "{{ username }}"
       password: aE87dRhcERj=!$2a
       state: present
       groups:
         - Users
