---
- hosts: win
  vars:
    username: myusername
  tasks:
    - name: "Add the my user"
      win_user:
       name: "{{ username }}"
       password: password
       state: present
       groups:
         - Users
