---
- name: Debug Playbook
  hosts: all
  become: true
  tasks:
    - name: Telnet package installation
      yum: name=telnet state=present
      register: output

    - name: Running debugger to show the output
      debug:
        var: output
