---
- name: Debug Playbook
  hosts: all
  tasks:
    - debug:
        msg: First task to Print debug message

    - debug:
        msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"
