---
- hosts: 172.31.6.203
  become: true
  tasks:
    - name: NTP OS Package Installation
      package: name=ntp state=present
    - name: NTP File Configurations
      file: path=/etc/ntp.conf state=file
      notify:
        - restart ntp 
    - name: To start NTP services
      service: name=ntpd state=started enabled=yes
  handlers:
    - name: restart ntp
      service: name=ntpd state=restarted
