---
- hosts: 172.31.10.150
  tasks:
    - name: NTP OS Package Installation
      package: name=ntp state=present
    - name: NTP File Configurations
      file: path=/etc/ntp.conf state=file
    - name: To start NTP services
      service: name=ntpd state=started enabled=yes
