---
- hosts: my-machine-ip
  become: yes
  tasks:
    - name: "Ensure group - groupname"
      group:
       name: groupname
       state: present
    - name: "Add the user - username "
      user:
       name: username
       comment: username 
       group: groupname
       update_password: on_create
