---
- hosts: my-machine-ip
  vars:
    username: jai
  tasks:
    - name: Ensure group - {{username}}
      group:
       name: {{username}}
       state: present
 
    - name: Add the user - {{username}}
      user:
       name: {{username}}
       comment: {{username}}
       group: {{username}}
       update_password: on_create
